#!/bin/bash

# Start Selenium
java -jar \
    tests/selenium.jar \
    -role node \
    -enablePassThrough false \
    -servlet org.openqa.grid.web.servlet.LifecycleServlet \
    -registerCycle 0 \
    -port 4444 > tests/_output/selenium.log 2>&1 &
sleep 2

# Start tests
codecept run acceptance --steps --html --coverage-html
